# Generated by Django 5.1.6 on 2025-02-21 12:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.PositiveIntegerField(default=1, validators=[core.validators.validate_length]),
        ),
    ]
