# Generated by Django 5.1.6 on 2025-02-21 13:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_active_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='', validators=[core.validators.validate_length]),
        ),
    ]
